[project]
name = "probabilistic-energy-modeling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "otii-tcp-client>=1.0.11",
    "pandas>=2.3.3",
    "scipy>=1.16.2",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
]
